import Layout from "../views/Layout/index.vue";

export default {
  path: "/pages-view",
  component: Layout,
  redirect: "/pages-view/file-folder",
  name: "PagesView",
  meta: {
    title: "FileFolder",
    icon: "mdi:book-open-page-variant-outline",
  },
  children: [
    {
      path: "file-folder",
      name: "Simple Folder",
      component: () => import("../components/PagesView/fileFolder.vue"),
      meta: {
        title: "Simple Folder Vue",
        link: "https://codepen.io/dropside/pen/RBwdjz",
      },
    },
    {
      path: "tree-ul",
      name: "Autogenerated JTree ",
      component: () => import("../components/PagesView/TreeUL.vue"),

      meta: {
        title: "Autogenerated Collapsible Directory Tree from a UL",
      },
    },
    {
      path: "flowchart-diagram",
      name: "Flowchart Diagram",
      component: () => import("../components/PagesView/flowchartDiagram.vue"),
      meta: {
        title: "Flowchart Diagram",
        link: "https://codepen.io/Mestika/pen/EarEoX",
      },
    },
    {
      path: "rain-thunder",
      name: "Raining with Thunder",
      component: () => import("../components/PagesView/rainBackground.vue"),
      meta: {
        title: "Raining with Thunder of Background",
      },
    },
    {
      path: "workout-30",
      name: "Workout 30 Days",
      component: () => import("../components/PagesView/workoutPage.vue"),
      meta: {
        title: "Workout 30 Days",
      },
    },
    {
      path: "faq",
      name: "FAQ Page",
      component: () => import("../components/PagesView/FAQPage.vue"),
      meta: {
        title: "FAQ Page",
      },
    },
    {
      path: "scroll-page",
      name: "Scroll Page",
      component: () => import("../components/PagesView/scroll.vue"),
      meta: {
        title: "Scroll Page ",
        link: "https://juejin.cn/post/7274346507036655656",
      },
    },
    {
      path: "image-slider",
      name: "Image Slider",
      component: () => import("../components/PagesView/ImageSlider.vue"),
      meta: {
        title: "Image Overlay Slider",
        link: "https://codepen.io/pizza3/pen/ZyGYRK",
      },
    },
    {
      path: "jagged-tabs",
      name: "Jagged Tabs",
      component: () => import("../components/PagesView/jaggedTabs.vue"),
      meta: { title: "Jagged Tabs", link: "https://codepen.io/jdniki/pen/PzZERJ" },
    },
    {
      path: "repeat-text-animation",
      name: "Repeat Text Animation",
      component: () => import("../components/PagesView/repeatTextAnimation.vue"),
      meta: {
        title: "Repeat Text Animation",
        link: "https://codepen.io/ozgursagiroglu/pen/bGEVpP",
      },
    },
    {
      path: "image-zoom",
      name: "Image Zoom",
      component: () => import("../components/PagesView/imageZoom.vue"),
      meta: {
        title: "Image Zoom",
        link: "https://codepen.io/suhajdab/pen/AaGJJQ",
      },
    },
    {
      path: "video-card",
      name: "Video Card",
      component: () => import("../components/PagesView/swipeableVideoCards.vue"),
      meta: {
        title: "Swipeable Video Cards",
        link: "https://codepen.io/mudrenok/pen/GjaJJj",
      },
    },
    {
      path: "summary-catalog",
      name: "Summary Catalog",
      component: () => import("../components/PagesView/summaryCatalog.vue"),
      meta: {
        title: "Summary Catalog",
        link: "https://codepen.io/Twikito/pen/edPQGb",
      },
    },
    {
      path: "scratch-canvas",
      name: "Scratch Canvas",
      component: () => import("../components/PagesView/scratchCanvas.vue"),
      meta: {
        title: "Scratch Canvas",
        link: "https://codepen.io/dudleystorey/pen/yJQxLX",
      },
    },
    {
      path: "css-solar-system",
      name: "CSS Solar System",
      component: () => import("../components/PagesView/cssSolarSystem.vue"),
      meta: {
        title: "CSS Solar System",
        link: "",
      },
    },
    {
      path: "nav-ajax-sites",
      name: "Nav Ajax Sites",
      component: () => import("../components/PagesView/navAjaxSites.vue"),
      meta: {
        title: "Nav Ajax Sites",
        link: "https://codepen.io/Bjurhager/pen/MwoMqa",
      },
    },
    {
      path: "elastic-sidebar",
      name: "Elastic Sidebar",
      component: () => import("../components/PagesView/elasticSidebar.vue"),
      meta: {
        title: "Elastic Sidebar",
        link: "https://codepen.io/suez/pen/emjwvP",
      },
    },
    {
      path: "directionally-hover",
      name: "Directionally Hover",
      component: () => import("../components/PagesView/directionallyHover.vue"),
      meta: {
        title: "Directionally Hover",
        link: "https://codepen.io/giana/pen/YZWjQy",
      },
    },
    {
      path: "svg-clip-path-hover",
      name: "Svg Clip-path Hover",
      component: () => import("../components/PagesView/svgClipPathHover.vue"),
      meta: {
        title: "Svg Clip Path Hover",
        link: "https://codepen.io/noeldelgado/pen/PZJGLx",
      },
    },
    {
      path: "order-process-steps",
      name: "Order Process Steps",
      component: () => import("../components/PagesView/orderProcessSteps.vue"),
      meta: {
        title: "Order Process Steps",
        link: "https://codepen.io/jcoulterdesign/pen/zdwajv",
      },
    },
    {
      path: "expand-card-page",
      name: "Expand Card Page",
      component: () => import("../components/PagesView/expandCardPage.vue"),
      meta: {
        title: "Expand Card Page",
        link: "https://codepen.io/rachsmith/pen/PWxoLN",
      },
    },
  ],
};
